[build]
builder = "nixpacks"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/"
healthcheckTimeout = 30
restartPolicyMaxRetries = 3

[[volumes]]
name = "mine_data"
mountPath = "/data"

[[volumes]]
name = "mine_uploads"
mountPath = "/app/public/uploads"
